// @prepros-append common-parts/start.js  
// @prepros-append common-parts/initialization.js  
// @prepros-append common-parts/phone-mask.js  
// @prepros-append common-parts/check-form.js  
// @prepros-append common-parts/edit-wp7.js 
// @prepros-append common-parts/img-cover.js  
// @prepros-append common-parts/style-file.js  
// @prepros-append common-parts/style-select.js  
// @prepros-append common-parts/btn-show-hide.js  
// @prepros-append common-parts/password-edit.js
// @prepros-append common-parts/simple.js
// @prepros-append common-parts/end.js
